# Generated by Django 5.2.7 on 2025-11-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_uz',
        ),
        migrations.AddField(
            model_name='product',
            name='color_hex',
            field=models.CharField(default='', help_text='Masalan: #FF5733', max_length=7, verbose_name='Rang HEX kodi'),
            preserve_default=False,
        ),
    ]
